# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: whisperChat    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18'                # set this to the node version to use
  REACT_VERSION: '18'                # set this to the react version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'

    - name: Set up React.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.REACT_VERSION }}
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
    
    - name: frontend npm install, build, and test
      run: |
        cd frontend/
        npm install
        npm run build --if-present
        #npm run test --if-present

    #- name: Build the frontend Docker image
    #  run: docker build frontend/

    - name: Zip frontend artifact for deployment
      run: zip -r frontend.zip * .env .next

    - name: Upload frontend artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: frontend.zip
        path: frontend.zip
        
    - name: backend npm install, build, and test
      run: |
        cd backend/
        npm install
        npm run build --if-present
        #npm run test --if-present

    #- name: Build the backend Docker image
    #  run: docker build backend/

    - name: Zip backend artifact for deployment
      run: zip -r backend.zip * .env .next        

    - name: Upload backend artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: backend.zip
        path: backend.zip           
 
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
    steps:
    - name: Download frontend artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: frontend.zip
        
    - name: unzip frontend artifact for deployment
      run: unzip frontend.zip  

    - name: Download backend artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: backend.zip

    - name: unzip backend artifact for deployment
      run: unzip backend.zip
  
    - name: 'Deploy whisperChat to Azure'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
